// These styles apply to every route in the application
import './globals.css';
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons:{
    icon:[
      {
        media: '(prefers-color-scheme: light)',
        url: '/images/favicon.svg',
        href : '/images/favicon.svg'
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/images/favicon.svg',
        href : '/images/favicon.svg'
      },
    ]
  }
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}